name: Step 4, Add RAG

on:
  workflow_dispatch:
  push:
    paths:
      - "data/**"
    branches:
      - main

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_data_directory:
    name: On addition of data directory
    needs: get_current_step

    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 4 }}

    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository to verify the data directory exists
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches

      - name: Check data directory exists
        id: check_data
        run: |
          if [ -d "data" ]; then
            echo "data_exists=true" >> $GITHUB_OUTPUT
          else
            echo "data_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Update to step 5
        if: steps.check_data.outputs.data_exists == 'true'
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 4
          to_step: 5