name: Step 5, Add Conversation Memory

on:
  workflow_dispatch:
  push:
    paths:
      - "packages/webapi/package.json"
    branches:
      - main

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_langchain_dependency:
    name: On addition of LangChain to package.json
    needs: get_current_step

    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 5 }}

    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository to verify the package.json content
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches

      - name: Check for LangChain in package.json
        id: check_langchain
        run: |
          if [ -f "packages/webapi/package.json" ] && grep -q "@langchain/openai" packages/webapi/package.json; then
            echo "langchain_exists=true" >> $GITHUB_OUTPUT
          else
            echo "langchain_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Update to step 6
        if: steps.check_langchain.outputs.langchain_exists == 'true'
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 5
          to_step: 6