name: Step 7, Connect Agent to MCP Tools

on:
  workflow_dispatch:
  push:
    paths:
      - "packages/**"
    branches:
      - main

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_agent_directory:
    name: On addition of node-os-mcp directory
    needs: get_current_step

    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 7 }}

    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository to verify the agent directory exists
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches

      - name: Check node-os-mcp directory exists
        id: check_node-os-mcp
        run: |
          if [ -d "packages/node-os-mcp" ]; then
            echo "agent_exists=true" >> $GITHUB_OUTPUT
          else
            echo "agent_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Update to step 8
        if: steps.check_node-os-mcp.outputs.node-os-mcp_exists == 'true'
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 7
          to_step: 8